services:
  bot:
    container_name: dev
    build: 
      context: .
      dockerfile: dev.Dockerfile
      args: 
        - DATABASE_URL:${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env