ARG VERSION="22"
FROM node:${VERSION}-alpine AS deploy
WORKDIR /app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ARG DISCORD_TOKEN
ENV DISCORD_TOKEN=${DISCORD_TOKEN}
ARG DISCORD_CLIENT
ENV DISCORD_CLIENT=${DISCORD_CLIENT}
ARG DISCORD_OWNER
ENV DISCORD_OWNER=${DISCORD_OWNER}

COPY . .
COPY <<EOF .env
DATABASE_URL=${DATABASE_URL}
DISCORD_TOKEN=${DISCORD_TOKEN}
DISCORD_CLIENT=${DISCORD_CLIENT}
DISCORD_OWNER=${DISCORD_OWNER}
EOF

RUN npm install
CMD npm run start:bot
