services:
  bot:
    build:
      context: .
      target: deploy
      args:
        - DATABASE_URL=${DATABASE_URL}
        - DISCORD_TOKEN=${DISCORD_TOKEN}
        - DISCORD_CLIENT=${DISCORD_CLIENT}
        - DISCORD_OWNER=${DISCORD_OWNER}
    env_file:
      - .env
    container_name: bot
