services:
  bot:
    env_file: .env
    environment:
      - PRIVATE=${PRIVATE}
      - PORT=${PORT}

    build:
      args:
        - PRIVATE=$PRIVATE
        - PORT=$PORT
      context: .
      target: production
