
  /**
   * This file is generated by the script generateListServices.ts
  */
  import type BuildEvent from '@/core/build/BuildEvent'
  import type BuildCommand from '@/core/build/BuildCommand'
  import type BuildMenu from '@/core/build/BuildMenu'
  import type BuildModal from '@/core/build/BuildModal'
  import type BuildButton from '@/core/build/BuildButtons'
  import guildMemberAdd from '@/events/guildMemberAdd/index'
import interactionCreate from '@/events/interactionsCreate/index'
import ready from '@/events/ready/index'
import canvas from '@/services/canvas/slash.index'
import colorCast from '@/services/colors/button.colorCast'
import deleteColor from '@/services/colors/button.deleteColorUser'
import colorPointer from '@/services/colors/button.startColors'
import selectColors from '@/services/colors/menu.selectColors'
import setting from '@/services/colors/settings/button.index'
import orderColors from '@/services/colors/settings/button.orderColors'
import settingRestartTemplate from '@/services/colors/settings/button.restartTemplate'
import settingsConfirmDeleteAll from '@/services/colors/settings/deleteOptions/button.confirmDeleteAll'
import settingsConfirmDeleteAsome from '@/services/colors/settings/deleteOptions/menu.deleteAsomeColors'
import settingsDeleteColors from '@/services/colors/settings/deleteOptions/menu.index'
import editColorsTemplate from '@/services/colors/settings/modal.editColorsTemplate'
import colors from '@/services/colors/slash.colors'
import linkDocumentation from '@/services/general/buttons/button.linkDocs'
import linkWeb from '@/services/general/buttons/button.linkWeb'
import linkDiscord from '@/services/general/buttons/linkDiscord.button'
import linkGithubIssues from '@/services/general/buttons/linkGithubIssues.button'
import linkKofi from '@/services/general/buttons/linkKofi.button'
import aboutme from '@/services/general/commands/aboutMe.command'

    export const events: Record<string, BuildEvent<any>> = {
      guildMemberAdd, interactionCreate, ready, 
    }
    export const commands: Record<string, BuildCommand> = {
      canvas, colors, aboutme, 
    }
    export const menus: Record<string, BuildMenu<any>> = {
      selectColors, settingsConfirmDeleteAsome, settingsDeleteColors, 
    }
    export const modals: Record<string, BuildModal> = {
      editColorsTemplate, 
    }
    export const buttons: Record<string, BuildButton> = {
      colorCast, deleteColor, colorPointer, setting, orderColors, settingRestartTemplate, settingsConfirmDeleteAll, linkDocumentation, linkWeb, linkDiscord, linkGithubIssues, linkKofi, 
    }
  