// This file is generated by the script generateListServices.ts
import type BuildButton from '@/core/build/BuildButtons'
import type BuildCommand from '@/core/build/BuildCommand'
import type BuildEvent from '@/core/build/BuildEvent'
import type BuildMenu from '@/core/build/BuildMenu'
import type BuildModal from '@/core/build/BuildModal'

// Events
import event_guildMemberAdd from '@/events/guildMemberAdd/index'
import event_interactionCreate from '@/events/interactionsCreate/index'
import event_ready from '@/events/ready/index'

// Services
import command_canvas from '@/services/canvas/slash.index'
import command_colors from '@/services/colors/slash.colors'
import command_aboutme from '@/services/general/commands/aboutMe.command'

import menu_selectColors from '@/services/colors/menu.selectColors'
import menu_settingsConfirmDeleteAsome from '@/services/colors/settings/deleteOptions/menu.deleteAsomeColors'
import menu_settingsDeleteColors from '@/services/colors/settings/deleteOptions/menu.index'

import modal_editColorsTemplate from '@/services/colors/settings/modal.editColorsTemplate'

import button_colorCast from '@/services/colors/button.colorCast'
import button_colors from '@/services/colors/button.deleteColorUser'
import button_colorPointer from '@/services/colors/button.startColors'
import button_setting from '@/services/colors/settings/button.index'
import button_orderColors from '@/services/colors/settings/button.orderColors'
import button_settingRestartTemplate from '@/services/colors/settings/button.restartTemplate'
import button_settingsConfirmDeleteAll from '@/services/colors/settings/deleteOptions/button.confirmDeleteAll'
import button_linkDocumentation from '@/services/general/buttons/button.linkDocs'
import button_linkWeb from '@/services/general/buttons/button.linkWeb'
import button_linkDiscord from '@/services/general/buttons/linkDiscord.button'
import button_linkGithubIssues from '@/services/general/buttons/linkGithubIssues.button'
import button_linkKofi from '@/services/general/buttons/linkKofi.button'

export const commands: Record<string, BuildCommand> = {
  canvas: command_canvas,
  colors: command_colors,
  aboutme: command_aboutme
}
export const events: Record<string, BuildEvent<any>> = {
  guildMemberAdd: event_guildMemberAdd,
  interactionCreate: event_interactionCreate,
  ready: event_ready
}
export const menus: Record<string, BuildMenu<any>> = {
  selectColors: menu_selectColors,
  settingsConfirmDeleteAsome: menu_settingsConfirmDeleteAsome,
  settingsDeleteColors: menu_settingsDeleteColors
}
export const modals: Record<string, BuildModal> = { editColorsTemplate: modal_editColorsTemplate }
export const buttons: Record<string, BuildButton> = {
  colorCast: button_colorCast,
  colors: button_colors,
  colorPointer: button_colorPointer,
  setting: button_setting,
  orderColors: button_orderColors,
  settingRestartTemplate: button_settingRestartTemplate,
  settingsConfirmDeleteAll: button_settingsConfirmDeleteAll,
  linkDocumentation: button_linkDocumentation,
  linkWeb: button_linkWeb,
  linkDiscord: button_linkDiscord,
  linkGithubIssues: button_linkGithubIssues,
  linkKofi: button_linkKofi
}
